# -----------------------------------------------------------------------------
# 🌊 Hay-Chan's Vibrant Mako Global Style Settings
# -----------------------------------------------------------------------------
font=Sans 11
background-color=#fef08add
text-color=#1c1917
width=360
height=150
margin=15,25,25,15
padding=16
border-size=3
border-color=#f97316
border-radius=16
progress-color=over #f59e0b
# Layout & Behavior
format=<b><span foreground='#f97316'>%s</span></b>\n%b
text-alignment=left
default-timeout=6000
layer=top
anchor=top-right

# Urgency Overrides
[urgency=low]
border-color=#f59e0b          
text-color=#44403c            
default-timeout=4000

[urgency=critical]
border-color=#ef4444
text-color=#fafaf9            
background-color=#ef4444dd
default-timeout=0
