# 🌊 Dark Deep-Sea Navy Client Colors !! (Amy's Sweater Edition)
set $blue_focused      #1e2942
set $blue_inactive     #111420
set $blue_text         #7e91b8
set $blue_indicator    #3b4261

# class                 border           background       text            indicator       child_border
client.focused          #3d59a1          $blue_focused    $blue_text      $blue_indicator #3d59a1
client.focused_inactive $blue_inactive   $blue_inactive   $blue_text      $blue_indicator $blue_inactive
client.unfocused        $blue_inactive   $blue_inactive   $blue_text      $blue_indicator $blue_inactive
