# -----------------------------------------------------------------------------
# 🌊 Hay-Chan's Vibrant Client Window Colors
# -----------------------------------------------------------------------------
# class                 border           backgr           text             indic            child_border
client.focused          #f97316          #fef08a          #1c1917          #f59e0b          #f97316
client.focused_inactive #f59e0b          #f59e0b          #1c1917          #f59e0b          #f59e0b
client.unfocused        #fef08a          #fef08a          #44403c          #fef08a          #fef08a
client.urgent           #ef4444          #ef4444          #fafaf9          #ef4444          #ef4444
