# -----------------------------------------------------------------------------
# 🦘 Sandy Yellow Theme Client Window Colors
# -----------------------------------------------------------------------------
# class                 border           backgr           text             indic            child_border
client.focused          #e9c46a          #f4a261          #264653          #f4a261          #e9c46a
client.focused_inactive #e2d4c9          #e2d4c9          #6d6875          #e2d4c9          #e2d4c9
client.unfocused        #e2d4c9          #e2d4c9          #6d6875          #e2d4c9          #e2d4c9
client.urgent           #e76f51          #e76f51          #ffffff          #e76f51          #e76f51
