# -----------------------------------------------------------------------------
# 🩵 Summer Nano Theme Client Window Colors - Metallic Key Borders
# -----------------------------------------------------------------------------
# class                 border           backgr           text             indic            child_border
client.focused          #94a3b8          #0a2271          #ffffff          #5b8ae4          #94a3b8
client.focused_inactive #081735          #081735          #94a3b8          #081735          #081735
client.unfocused        #081735          #081735          #94a3b8          #081735          #081735
client.urgent           #dc2626          #dc2626          #ffffff          #dc2626          #dc2626
