# -----------------------------------------------------------------------------
# 🌊 SnowyEgret Signature Client Window Colors
# -----------------------------------------------------------------------------
# class                 border           backgr           text             indic            child_border
client.focused          #B9E28C          #5B507A          #BFD7EA          #D6D84F          #B9E28C
client.focused_inactive #5B618A          #5B618A          #9EADC8          #5B618A          #5B618A
client.unfocused        #5B507A          #5B507A          #9EADC8          #5B507A          #5B507A
client.urgent           #0A8754          #0A8754          #BFD7EA          #0A8754          #0A8754
