# 🌸 Cute Strawberry Pink Vibe Client Colors !! ✨

# class                 border  backgr  text    indic   child_border
client.focused          #d48da3 #d48da3 #ffffff #a66275 #d48da3
client.focused_inactive #2e2329 #2e2329 #cca3af #2e2329 #2e2329
client.unfocused        #251c21 #251c21 #cca3af #251c21 #251c21
client.urgent           #7a4848 #7a4848 #ffffff #7a4848 #7a4848
