# -----------------------------------------------------------------------------
# 🐈‍⬛ Venom Theme Client Window Colors (Darker Green Edition)
# -----------------------------------------------------------------------------
# class                 border           backgr           text             indic            child_border
client.focused          #1db954          #1a1a1a          #ffffff          #1aa34a          #1db954
client.focused_inactive #121212          #121212          #757575          #121212          #121212
client.unfocused        #121212          #121212          #757575          #121212          #121212
client.urgent           #ff3333          #ff3333          #ffffff          #ff3333          #ff3333
