# -----------------------------------------------------------------------------
# Green & Clean Global Style Settings
# -----------------------------------------------------------------------------
font=Sans 11
background-color=#141f17dd
text-color=#f2f7f4
width=360
height=150
margin=15,25,25,15
padding=16
border-size=2
border-color=#a7f3d0
border-radius=16
progress-color=over #065f46

# Icons configuration
icons=1
max-icon-size=48
icon-location=left
icon-border-radius=8

# Layout & Behavior
format=<b><span foreground='#34d399'>%s</span></b>\n%b
text-alignment=left
default-timeout=6000
ignore-timeout=0
layer=top
anchor=top-right

# -----------------------------------------------------------------------------
# Urgency Overrides
# -----------------------------------------------------------------------------

# Low Urgency (e.g., subtle status changes, music tracks)
[urgency=low]
border-color=#064e3b
text-color=#6ee7b7
default-timeout=4000

# High / Critical Urgency (e.g., low battery, system errors)
[urgency=critical]
border-color=#f43f5e
text-color=#fda4af
default-timeout=0
